print('Ola mundo!')
print('Ser romântico às vezes ajuda')
print('Mas se fecho os olhos, te imagino nua')
print('Talvez pareça uma cena de Hollywood')
print('Se tá pensando isso, por favor, não se ilude')
print('Eu só quero uma noite de amor')
print('Como as outras, só mais uma que passou')
print('Mas foi só a porta fechar')
print('Pra mudar minha cabeça')
print('A sua boca vale o preço')
print('Pra perder o sossego que eu tinha')
print('A lua até beijou o mar')
print('Pra não ficar de vela ficar de vela')
print('Os quatro perdidos de amor')
print('Eu, você, o mar e ela')
print('Eu, você, o mar e ela')
print('Ser romântico às vezes ajuda')
print('Mas se fecho os olhos, te imagino nua')
print('Talvez pareça uma cena de Hollywood')
print('Se tá pensando isso, por favor, não se ilude')
print('Eu só quero uma noite de amor')
print('Como as outras, só mais uma que passou')
print('Mas foi só a porta fechar')
print('Pra mudar minha cabeça')
print('A sua boca vale o preço')
print('Pra perder o sossego que eu tinha')
print('A lua até beijou o mar')
print('Pra não ficar de vela')
print('Os quatro perdidos de amor')
print('Eu, você, o mar e ela')
print('Eu, você, o mar e ela')
print('Mas foi só a porta fechar')
print('Pra mudar minha cabeça')
print('A sua boca vale o preço')
print('Pra perder o sossego que eu tinha')
print('A lua até beijou o mar')
print('Pra não ficar de vela ')
print('Os quatro perdidos de amor')
print('Eu, você, o mar e ela')
print('Eu, você, o mar e ela')
print('Eu, você... o mar e ela ')